import Head from 'next/head';
import styled from '@emotion/styled';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<h1>Hola</h1>
			</div>
		</div>
	);
}
